@startuml

!theme plain
skinparam roundcorner 10
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

' DISCLAIMER: le tabelle ponte, per gestire la molteplicità, tra le entità Shipment, Customer e Driver sono state volutamente omesse per una migliore leggibilità

' DOMINIO NORMATIVO (ADR / UN)

entity "adr_class" as Classes {
  * id : Long <<PK>>
  --
  * class_code : String <<UQ>>
  * description : String
}

entity "onu_number" as UN {
  * id : Long <<PK>>
  --
  * adr_class_id : Long <<FK>>
  --
  * onu_code : String <<UQ>>
  * name : String
  * kemler_code : String
  * packing_group : enum
  * physical_state : enum
  * tunnel_restriction : enum
  * transport_category : Integer
}

entity "compatibility_rule" as Rules {
  * id : Long <<PK>>
  --
  * adr_class_a_id : Long <<FK>>
  * adr_class_b_id : Long <<FK>>
  --
  * is_compatible : Boolean
  * warning_note : String
}

' DOMINIO ANAGRAFICHE (Master Data - No FK Spedizioni)

entity "vehicle" as Vehicles {
  * id : Long <<PK>>
  --
  * license_plate : String <<UQ>>
  * vehicle_type : enum
  * max_weight_kg : Integer
  * active : boolean
}

entity "customer" as Customer {
	* id : Long <<PK>>
	--
	* company_name : String
	* vat_number : String <<UQ>>
	* legal_address : String
    * active : boolean
}

entity "driver" as Driver {
	* id : Long <<PK>>
	--
	* full_name : String
	* tax_code : String <<UQ>>
	* license_number : String <<UQ>>
	* cqc : boolean
	* active : boolean
}

entity "adr_driver_approval" as DriverApproval {
	--
	* driver_id : Long <<FK>>
	--
	* driver_approval : enum
}

' DOMINIO TRANSAZIONALE (La Spedizione)

entity "shipment" as Shipments {
  * id : Long <<PK>>
  --
  * vehicle_id : Long <<FK>
  * driver_id : Long <<FK>>
  * customer_id : Long <<FK>>
  --
  * tracking_number : String <<UQ>>
  * shipment_date : Timestamp
  * status : enum
  * origin_address : String
  * destination_address : String
}

entity "shipment_item" as Items {
  * id : Long <<PK>>
  --
  * shipment_id : Long <<FK>>
  * onu_number_id : Long <<FK>>
  --
  * item_uuid : String
  * quantity : Float
  * unit_of_measure : enum
}

entity "package_info" as PackageInfo {
	* id : Long <<PK>>
	--
	* shipment_item_id : Long <<FK>>
	--
	* n_package : Integer
	* description : String
}

entity "shipment_route" as ShipmentRoute {
	* id : Long <<PK>>
	--
	* shipment_id : Long <<FK>>
	--
	* orgn_lat : Double
	* dest_lat : Double
	* distance_km : Float
}

' DOMINIO SNAPSHOT LEGALI (Shadow Tables / Join Tables)

entity "shipment_vehicle_snapshot" as VehicleSnapshot {
    * id : Long <<PK>>
	--
	* shipment_id : Long <<FK>>
    --
	* snap_license_plate : String
	* snap_vehicle_type : enum
	* snap_max_weight_kg : Integer
}

entity "shipment_driver_snapshot" as DriverSnapshot {
    * id : Long <<PK>>
	--
	* shipment_id : Long <<FK>>
    --
	* snap_full_name : String
	* snap_tax_code : String 
	* snap_license_number : String
	* snap_cqc : boolean
    * snap_adr_approvals : String
}

entity "shipment_customer_snapshot" as CustomerSnapshot {
	* id : Long <<PK>>
	--
	* shipment_id : Long <<FK>>
	--
    * snap_role : enum <<Sender, Receiver, Carrier>>
	* snap_company_name : String
	* snap_vat_number : String
	* snap_legal_address : String
	--
    UniqueKey(shipment_id, snap_role)
}

' RELAZIONI

Classes "1 " ||--o{ "1 " UN
Classes ||--o{ Rules : "Class A"
Classes ||--o{ Rules : "Class B"

Vehicles "1\t" ||--|| "1\t" Shipments
Driver "1..2\t" ||--|{ "1 " Shipments
Customer "3 " ||--|{ "1 " Shipments
Shipments "1  " ||--|{ "n " Items
UN "1\t" ||--o{ "n\t" Items
Shipments "1" ||--|| "1..n " ShipmentRoute
Items "1 " ||--o| "0..1\t" PackageInfo
Driver "1" ||--o{ "n" DriverApproval

' Relazioni Spedizione -> Snapshot (Il "Congelamento")
Shipments "1 " ||--|| "1 " VehicleSnapshot : " (Veicolo Congelato)"
Shipments "1\t" ||--|{ "1..2     " DriverSnapshot : " (Autisti Congelati)"
Shipments "1" ||--|{ "3" CustomerSnapshot : " (Clienti Congelati)"

@enduml